// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspiCore.Data;

#nullable disable

namespace aspiCore.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspiCore.Model.DanhMucMon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucMons");
                });

            modelBuilder.Entity("aspiCore.Model.DatLich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("IdKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDat")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdKhoaHoc");

                    b.ToTable("DatLichs");
                });

            modelBuilder.Entity("aspiCore.Model.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DanhGiaTrungBinh")
                        .HasColumnType("float");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<string>("LichTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoiIch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoChoConTrong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdGiaoVien");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("aspiCore.Model.KhoaHocMonAn", b =>
                {
                    b.Property<int>("IdKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("IdMonAn")
                        .HasColumnType("int");

                    b.HasKey("IdKhoaHoc", "IdMonAn");

                    b.HasIndex("IdMonAn");

                    b.ToTable("KhoaHocMonAns");
                });

            modelBuilder.Entity("aspiCore.Model.MonAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDanhMuc");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("aspiCore.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("aspiCore.Model.DatLich", b =>
                {
                    b.HasOne("aspiCore.Model.User", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("aspiCore.Model.KhoaHoc", "KhoaHoc")
                        .WithMany("DatLichs")
                        .HasForeignKey("IdKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("aspiCore.Model.KhoaHoc", b =>
                {
                    b.HasOne("aspiCore.Model.User", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("IdGiaoVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("aspiCore.Model.KhoaHocMonAn", b =>
                {
                    b.HasOne("aspiCore.Model.KhoaHoc", "KhoaHoc")
                        .WithMany("KhoaHocMonAns")
                        .HasForeignKey("IdKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspiCore.Model.MonAn", "MonAn")
                        .WithMany("KhoaHocMonAns")
                        .HasForeignKey("IdMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("aspiCore.Model.MonAn", b =>
                {
                    b.HasOne("aspiCore.Model.DanhMucMon", "DanhMucMon")
                        .WithMany("MonAns")
                        .HasForeignKey("IdDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucMon");
                });

            modelBuilder.Entity("aspiCore.Model.DanhMucMon", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("aspiCore.Model.KhoaHoc", b =>
                {
                    b.Navigation("DatLichs");

                    b.Navigation("KhoaHocMonAns");
                });

            modelBuilder.Entity("aspiCore.Model.MonAn", b =>
                {
                    b.Navigation("KhoaHocMonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
